language: node_js
node_js:
 - "stable"
install:
 - rm -rf node_modules && rehash -r && npm install
script:
 - npm test
 - npm run build || true
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: build
 on:
   branch: master